# Generated by Django 4.0.1 on 2022-01-22 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_properties_latitud_properties_longitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='properties',
            old_name='predio',
            new_name='propietario',
        ),
        migrations.RemoveField(
            model_name='properties',
            name='name_propietario',
        ),
    ]
